#!/bin/bash

name=simsun-more
oname=fmsong
for size in 6; do
    ./ttf2upf -p $size -t $oname -o $oname-ascii-$size.upf $name.ttc
done

name=simsun-more
oname=fmsong
for size in 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31; do
    ./ttf2upf -p $size -t $oname -o $oname-ascii-gbk-$size.upf $name.ttc
done

name=simsun-more
oname=fmsong
for size in 7 8 9; do
    ./ttf2upf -p $size -t $oname -o $oname-ascii-gb2312-$size.upf $name.ttc
done

