#!/bin/bash

name=simsun
oname=fmsong
for size in 12 13 14 15 16 18; do
    ./ttf2qpf -p $size -o $oname-gbk-$size.qpf $name.ttc
done

name=simhei
oname=fmhei
for size in 16 18 20; do
    ./ttf2qpf -p $size -o $oname-gbk-$size.qpf $name.ttf
done

